# Goals for this workbook:
1. import the data
2. store the data in an array
3. group the data by class and split into groups (basically array operations)
4. compute distance between vectors of parameters
5. randomize the order of lists
6. develop a nearest neighbor algorithm
        -- Pick starting vertex
        -- Travel to the neighbor with the cheapest cost
        -- Continue traveling to new neighbor with least cost
        -- Complete cycle after visiting all cities

In [37]:
import numpy as np
import pandas as pd
import matplotlib as plt
import sklearn
import seaborn as sb
from pandas import Series, DataFrame

In [74]:
# read in file as a data frame using pandas and convert to numpy array
irisData = pd.read_csv('practice/iris.data', names=['sepLen', 'sepWdth', 'petLen', 'petWdth', 'class'])
irisArray = irisData.to_numpy()
irisData

sepLen  sepWdth  petLen  petWdth           class
0       5.1      3.5     1.4      0.2     Iris-setosa
1       4.9      3.0     1.4      0.2     Iris-setosa
2       4.7      3.2     1.3      0.2     Iris-setosa
3       4.6      3.1     1.5      0.2     Iris-setosa
4       5.0      3.6     1.4      0.2     Iris-setosa
5       5.4      3.9     1.7      0.4     Iris-setosa
6       4.6      3.4     1.4      0.3     Iris-setosa
7       5.0      3.4     1.5      0.2     Iris-setosa
8       4.4      2.9     1.4      0.2     Iris-setosa
9       4.9      3.1     1.5      0.1     Iris-setosa
10      5.4      3.7     1.5      0.2     Iris-setosa
11      4.8      3.4     1.6      0.2     Iris-setosa
12      4.8      3.0     1.4      0.1     Iris-setosa
13      4.3      3.0     1.1      0.1     Iris-setosa
14      5.8      4.0     1.2      0.2     Iris-setosa
15      5.7      4.4     1.5      0.4     Iris-setosa
16      5.4      3.9     1.3      0.4     Iris-setosa
17      5.1      3.5     1.4      0.3     Iris-setosa
18      5.7      3.8     1.7      0.3     Iris-setosa
19      5.1      3.8     1.5      0.3     Iris-setosa
20      5.4      3.4     1.7      0.2     Iris-setosa
21      5.1      3.7     1.5      0.4     Iris-setosa
22      4.6      3.6     1.0      0.2     Iris-setosa
23      5.1      3.3     1.7      0.5     Iris-setosa
24      4.8      3.4     1.9      0.2     Iris-setosa
25      5.0      3.0     1.6      0.2     Iris-setosa
26      5.0      3.4     1.6      0.4     Iris-setosa
27      5.2      3.5     1.5      0.2     Iris-setosa
28      5.2      3.4     1.4      0.2     Iris-setosa
29      4.7      3.2     1.6      0.2     Iris-setosa
..      ...      ...     ...      ...             ...
120     6.9      3.2     5.7      2.3  Iris-virginica
121     5.6      2.8     4.9      2.0  Iris-virginica
122     7.7      2.8     6.7      2.0  Iris-virginica
123     6.3      2.7     4.9      1.8  Iris-virginica
124     6.7      3.3     5.7      2.1  Iris-virginica
125     7.2      3.2     6.0      1.8  Iris-virginica
126     6.2      2.8     4.8      1.8  Iris-virginica
127     6.1      3.0     4.9      1.8  Iris-virginica
128     6.4      2.8     5.6      2.1  Iris-virginica
129     7.2      3.0     5.8      1.6  Iris-virginica
130     7.4      2.8     6.1      1.9  Iris-virginica
131     7.9      3.8     6.4      2.0  Iris-virginica
132     6.4      2.8     5.6      2.2  Iris-virginica
133     6.3      2.8     5.1      1.5  Iris-virginica
134     6.1      2.6     5.6      1.4  Iris-virginica
135     7.7      3.0     6.1      2.3  Iris-virginica
136     6.3      3.4     5.6      2.4  Iris-virginica
137     6.4      3.1     5.5      1.8  Iris-virginica
138     6.0      3.0     4.8      1.8  Iris-virginica
139     6.9      3.1     5.4      2.1  Iris-virginica
140     6.7      3.1     5.6      2.4  Iris-virginica
141     6.9      3.1     5.1      2.3  Iris-virginica
142     5.8      2.7     5.1      1.9  Iris-virginica
143     6.8      3.2     5.9      2.3  Iris-virginica
144     6.7      3.3     5.7      2.5  Iris-virginica
145     6.7      3.0     5.2      2.3  Iris-virginica
146     6.3      2.5     5.0      1.9  Iris-virginica
147     6.5      3.0     5.2      2.0  Iris-virginica
148     6.2      3.4     5.4      2.3  Iris-virginica
149     5.9      3.0     5.1      1.8  Iris-virginica

[150 rows x 5 columns]

In [39]:
# group by class
irisByClass = irisData.groupby("class")


In [44]:
# find disatance
u = [1,2,3]
v = [4,5,6]
from scipy.spatial import distance
distance.euclidean(u,v)

5.196152422706632

In [41]:
# randomize the order of lists
import random
random.shuffle(x)

In [45]:
# nearest neighbor algorithm

# split data into attributes and labels
attributes = irisData.iloc[:, :-1].values  
labels = irisData.iloc[:, -1].values 

# split data into testing/training groups
from sklearn.model_selection import train_test_split  
X_train, X_test, y_train, y_test = train_test_split(attributes, labels, test_size=0.10)

# scale data for uniform evaluation of distance functions
from sklearn.preprocessing import StandardScaler  
scaler = StandardScaler()  
scaler.fit(X_train)

X_train = scaler.transform(X_train)  
X_test = scaler.transform(X_test)  

# train KNN algorithm
from sklearn.neighbors import KNeighborsClassifier  
classifier = KNeighborsClassifier(n_neighbors=5)     # first parameter arbitrary; adjust with testing/eval
classifier.fit(X_train, y_train)  
# can do this part manually by defining a distance function of choice and a get neighbors function

# test the model
y_pred = classifier.predict(X_test)  

# evaluate the algorithm
from sklearn.metrics import classification_report, confusion_matrix  
print(confusion_matrix(y_test, y_pred))  
print(classification_report(y_test, y_pred))  

[[5 0 0]
 [0 3 0]
 [0 0 7]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00         5
Iris-versicolor       1.00      1.00      1.00         3
 Iris-virginica       1.00      1.00      1.00         7

      micro avg       1.00      1.00      1.00        15
      macro avg       1.00      1.00      1.00        15
   weighted avg       1.00      1.00      1.00        15



In [58]:
# adjust the value of K to minimize error
error = []

# Calculating error for K values between 1 and 40
for i in range(1, 40):  
    knn = KNeighborsClassifier(n_neighbors=i)
    knn.fit(X_train, y_train)
    pred_i = knn.predict(X_test)
    error.append(np.mean(pred_i != y_test))
    
# plot the calculated error for K values
# plt.figure(figsize=(12, 6))  
# plt.plot(range(1, 40), error, color='red', linestyle='dashed', marker='o',  
#          markerfacecolor='blue', markersize=10)
# plt.title('Error Rate K Value')  
# plt.xlabel('K Value')  
# plt.ylabel('Mean Error')  

AttributeError: module 'matplotlib' has no attribute 'plot'

## Next steps

* randomize how data is split
* key to nearest neighbor algorithm: how the data is clustered (i.e. the distance function)
    * preprocessing to improve
        * look at data; do any data contribute more to skew
        * want to normalize the data for each column (subtract mean; divide by std dev)
    * use different distance functions
        * change weights of parameters in the distance function
* organize code into classes, functions

* euclidean distance formula
* 2 more distance formulas
* split data into known and unknown groups
* loop over unknown to find the closest known and guess class
* compare guess with true value to get % correct